PERMISSION_MATRIX = {
    "REPORTER": {
        "report": ["create", "read_own", "update_draft", "submit", "evidence_upload"],
        "case": ["read_own", "read_notes", "respond"],
        "message": ["send", "read"],
        "user": [],
        "analytics": [],
    },
    "OFFICER": {
        "report": ["read_own", "read_all", "update_status", "assign"],
        "case": [
            "read_own",
            "read_all",
            "update",
            "assign",
            "transition",
            "add_note",
            "read_notes",
            "request_information",
        ],
        "message": ["send", "read"],
        "user": [],
        "analytics": ["view"],
    },
    "ADMIN": {
        "report": [
            "create",
            "read_own",
            "read_all",
            "update_status",
            "update_draft",
            "assign",
            "close",
            "submit",
            "evidence_upload",
        ],
        "case": [
            "create",
            "read_own",
            "read_all",
            "update",
            "assign",
            "transition",
            "add_note",
            "read_notes",
            "request_information",
            "close",
            "respond",
        ],
        "message": ["send", "read"],
        "user": ["manage"],
        "analytics": ["view"],
    },
}
