# Generated by Django 5.2.17 on 2026-08-23 15:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "code",
                    models.CharField(
                        blank=True, default="", max_length=30, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Campus",
                "verbose_name_plural": "Campuses",
                "db_table": "campuses",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="report",
            name="suspect_details",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="report",
            name="suspect_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("student", "Student"),
                    ("lecturer", "Lecturer"),
                    ("staff", "Staff member"),
                    ("visitor", "Visitor"),
                    ("other", "Other / not sure"),
                ],
                default="",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="victim_gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("female", "Girl / woman"),
                    ("male", "Boy / man"),
                    ("non_binary", "Non-binary / another identity"),
                    ("self_describe", "Self-describe"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                default="",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="campus_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="reports.campus",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="suspect_campus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suspect_reports",
                to="reports.campus",
            ),
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, default="", max_length=30)),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="reports.campus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "db_table": "departments",
                "ordering": ["campus__name", "name"],
            },
        ),
        migrations.AddField(
            model_name="report",
            name="department_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="reports.department",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="suspect_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suspect_department_reports",
                to="reports.department",
            ),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                fields=("campus", "name"), name="uq_department_campus_name"
            ),
        ),
    ]
