# Generated by Django 5.2.16 on 2026-07-22 12:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_create_role_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("report_submitted", "Report Submitted"),
                            ("case_assigned", "Case Assigned"),
                            ("officer_replied", "Officer Replied"),
                            ("info_requested", "Information Requested"),
                            ("status_changed", "Status Changed"),
                            ("case_closed", "Case Closed"),
                            ("new_report_officer", "New Report for Officers"),
                            ("reporter_replied", "Reporter Replied"),
                            ("evidence_uploaded", "Evidence Uploaded"),
                            ("critical_incident_alert", "Critical Incident Alert"),
                        ],
                        max_length=50,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "recipient_anonymous_reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="accounts.anonymousreporter",
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("recipient_anonymous_reporter__isnull", True),
                                ("recipient_user__isnull", False),
                            ),
                            models.Q(
                                ("recipient_anonymous_reporter__isnull", False),
                                ("recipient_user__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="chk_notification_single_recipient",
                    )
                ],
            },
        ),
    ]
