# Generated by Django 5.2.16 on 2026-07-22 11:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_REVIEW", "Pending Review"),
                            ("ASSIGNED", "Assigned"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("AWAITING_REPORTER_RESPONSE", "Awaiting Reporter Response"),
                            ("UNDER_INVESTIGATION", "Under Investigation"),
                            ("REFERRED", "Referred"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                            ("REOPENED", "Reopened"),
                        ],
                        default="PENDING_REVIEW",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_summary", models.TextField(blank=True, default="")),
                (
                    "assigned_officer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case",
                        to="reports.report",
                    ),
                ),
            ],
            options={
                "verbose_name": "Case",
                "verbose_name_plural": "Cases",
                "db_table": "cases",
            },
        ),
        migrations.CreateModel(
            name="CaseNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("note_text", models.TextField()),
                ("is_internal", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="cases.case",
                    ),
                ),
            ],
            options={
                "verbose_name": "Case Note",
                "verbose_name_plural": "Case Notes",
                "db_table": "case_notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InformationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("request_text", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("FULFILLED", "Fulfilled")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("reporter_response", models.TextField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="information_requests",
                        to="cases.case",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Information Request",
                "verbose_name_plural": "Information Requests",
                "db_table": "information_requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
